apiVersion: v1
kind: Namespace
metadata:
  name: rolling-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactui
  namespace: rolling-ns
  labels:
    app: reactui
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: reactui
  template:
    metadata:
      labels:
        app: reactui
    spec:
      containers:
        - name: reactui
          image: amitabhdevops/online_shop
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: ru-service
  namespace: rolling-ns
spec:
  type: LoadBalancer
  selector:
    app: reactui
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      
