apiVersion: v1
kind: Namespace
metadata:
  name: recreate-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop
  namespace: recreate-ns
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      labels:
        app: online-shop
    spec:
      containers:
      - name: online-shop
        image: amitabhdevops/online-shop
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: recreate-service
  namespace: recreate-ns
spec:
  type: NodePort
  selector:
    app: online-shop
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
